# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 16:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hollau', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='\u0434\u0430\u0442\u0430')),
                ('price', models.IntegerField(verbose_name='\u043d\u043e\u0432\u0430\u044f \u0446\u0435\u043d\u0430')),
            ],
            options={
                'verbose_name': '\u041f\u0440\u0435\u0434\u043b\u043e\u0436\u0435\u043d\u0438\u0435',
                'verbose_name_plural': '\u041f\u0440\u0435\u0434\u043b\u043e\u0436\u0435\u043d\u0438\u044f',
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, verbose_name='\u043f\u0440\u0435\u0434\u043b\u043e\u0436\u0435\u043d\u0438\u0435')),
                ('description', models.TextField(verbose_name='\u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u043f\u0440\u0435\u0434\u043b\u043e\u0436\u0435\u043d\u0438\u044f')),
                ('start_price', models.IntegerField(verbose_name='\u0441\u0442\u0430\u0440\u0442\u043e\u0432\u0430\u044f \u0446\u0435\u043d\u0430')),
                ('current_price', models.IntegerField(blank=True, verbose_name='\u0442\u0435\u043a\u0443\u0449\u0430\u044f \u0446\u0435\u043d\u0430')),
                ('sold', models.BooleanField(verbose_name='\u043f\u0440\u043e\u0434\u0430\u043d\u043e')),
                ('start_date', models.DateTimeField(verbose_name='\u043d\u0430\u0447\u0430\u043b\u043e \u043f\u0440\u043e\u0434\u0430\u0436\u0438')),
                ('end_date', models.DateTimeField(verbose_name='\u043e\u043a\u043e\u043d\u0447\u0430\u043d\u0438\u0435 \u043f\u0440\u043e\u0434\u0430\u0436\u0438')),
                ('lastest_propose', models.DateTimeField(blank=True, null=True, verbose_name='\u043f\u043e\u0441\u043b\u0435\u0434\u043d\u0435\u0435 \u043f\u0440\u0435\u0434\u043b\u043e\u0436\u0435\u043d\u0438\u0435')),
                ('author', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='lots', to=settings.AUTH_USER_MODEL, verbose_name='\u0410\u0443\u043a\u0446\u0438\u043e\u043d\u0430\u0442\u043e\u0440')),
            ],
            options={
                'verbose_name': '\u041b\u043e\u0442',
                'verbose_name_plural': '\u041b\u043e\u0442\u044b',
            },
        ),
        migrations.AddField(
            model_name='bet',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hollau.Lot', verbose_name='\u043b\u043e\u0442'),
        ),
        migrations.AddField(
            model_name='bet',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
