# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 10:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hollau', '0003_auto_20160912_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hollau.Category', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f'),
        ),
    ]
