# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 09:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hollau', '0005_auto_20160912_1027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bet',
            options={'verbose_name': '\u0421\u0442\u0430\u0432\u043a\u0430', 'verbose_name_plural': '\u0421\u0442\u0430\u0432\u043a\u0438'},
        ),
    ]
