# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hollau', '0006_auto_20160913_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='current_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u0442\u0435\u043a\u0443\u0449\u0430\u044f \u0446\u0435\u043d\u0430'),
        ),
    ]
