# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hollau', '0013_auto_20160915_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='current_price',
            field=models.FloatField(blank=True, null=True, verbose_name='\u0442\u0435\u043a\u0443\u0449\u0430\u044f \u0446\u0435\u043d\u0430'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='start_price',
            field=models.FloatField(verbose_name='\u0441\u0442\u0430\u0440\u0442\u043e\u0432\u0430\u044f \u0446\u0435\u043d\u0430'),
        ),
    ]
