# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-28 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hollau', '0014_auto_20160915_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='location',
            field=models.TextField(default='\u041c\u0438\u043d\u0441\u043a, \u0411\u0435\u043b\u0430\u0440\u0443\u0441\u044c', max_length=100, verbose_name='\u043b\u043e\u043a\u0430\u0446\u0438\u044f'),
        ),
    ]
