# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-28 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hollau', '0016_auto_20160928_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='location',
            field=models.CharField(default='', max_length=100, verbose_name='\u043b\u043e\u043a\u0430\u0446\u0438\u044f'),
        ),
    ]
