# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-28 17:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hollau', '0017_auto_20160928_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='', max_length=100, verbose_name='\u043b\u043e\u043a\u0430\u0446\u0438\u044f')),
            ],
        ),
        migrations.AlterField(
            model_name='lot',
            name='author',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='lots', to=settings.AUTH_USER_MODEL, verbose_name='\u0430\u0443\u043a\u0446\u0438\u043e\u043d\u0430\u0442\u043e\u0440'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hollau.Category', verbose_name='\u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='location',
            field=models.ForeignKey(default='', max_length=100, on_delete=django.db.models.deletion.CASCADE, to='hollau.Location', verbose_name='\u043b\u043e\u043a\u0430\u0446\u0438\u044f'),
        ),
    ]
