# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-28 17:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hollau', '0018_auto_20160928_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30, verbose_name='\u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='author',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='lots', to=settings.AUTH_USER_MODEL, verbose_name='\u0410\u0443\u043a\u0446\u0438\u043e\u043d\u0430\u0442\u043e\u0440'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='location',
            field=models.CharField(default='', max_length=100, verbose_name='\u043b\u043e\u043a\u0430\u0446\u0438\u044f'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
