# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-29 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hollau', '0020_auto_20160929_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='userlocation',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='\u043c\u0435\u0441\u0442\u043e\u043f\u043e\u043b\u043e\u0436\u0435\u043d\u0438\u0435'),
        ),
    ]
