# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-29 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hollau', '0021_auto_20160929_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='\u044d\u043b\u0435\u043a\u0442\u0440\u043e\u043d\u043d\u044b\u0439 \u0430\u0434\u0440\u0435\u0441'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='\u0438\u043c\u044f'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='surname',
            field=models.CharField(max_length=50, null=True, verbose_name='\u0444\u0430\u043c\u0438\u043b\u0438\u044f'),
        ),
    ]
