# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-30 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hollau', '0022_auto_20160929_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='surname',
            new_name='last_name',
        ),
    ]
