# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-11 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hollau', '0023_auto_20160930_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='price',
            field=models.FloatField(verbose_name='\u043d\u043e\u0432\u0430\u044f \u0446\u0435\u043d\u0430'),
        ),
    ]
